#!/usr/bin/env python3
"""
👻 GHOST HUNT DELUXE — Enhanced snake-to-ghost-hunt transformer.

Reads:   assets/ghost-hunt-game.svg  (generated by Platane/snk)
Writes:  assets/ghost-hunt-game.svg  (overwrites with enhanced game version)

Takes the Platane/snk contribution snake and transforms it into a
rich, game-themed visualization with animated ghosts, sparkles,
HUD overlay, and purple-ghost recoloring.
"""
from __future__ import annotations

import random
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

INPUT = Path("assets/ghost-hunt-game.svg")
OUTPUT = INPUT

PURPLE = "#8b5cf6"
PURPLE_LIGHT = "#a78bfa"
PURPLE_DIM = "#6d28d9"
PURPLE_BG = "#1a0b2e"
GOLD = "#fbbf24"
CYAN = "#22d3ee"
PINK = "#f472b6"

ACTIVE_FILLS = {
    "#0e4429", "#006d32", "#26a641", "#39d353",
    "#9be9a8", "#40c463", "#30a14e", "#216e39",
}

EMPTY_FILLS = {
    "#161b22", "#ebedf0", "#0d1117", "none", "transparent",
}

EXTRA_CSS = """
    /* Ghost Hunt Deluxe theme */
    svg path  { stroke: #8b5cf6 !important; }
    svg circle { fill: #8b5cf6 !important; }
    @keyframes ghostFloat{0%,100%{transform:translateY(0);opacity:0.9}50%{transform:translateY(-5px);opacity:0.5}}
    @keyframes ghostGlow{0%,100%{filter:drop-shadow(0 0 3px #8b5cf6)}50%{filter:drop-shadow(0 0 12px #c084fc)}}
    @keyframes sparkle{0%,100%{opacity:0;transform:scale(0.3)}50%{opacity:1;transform:scale(1.3)}}
    @keyframes hudPulse{0%,100%{opacity:0.85}50%{opacity:1}}
    .ghost{animation:ghostFloat 3s ease-in-out infinite,ghostGlow 2s ease-in-out infinite}
    .sparkle{animation:sparkle 1s ease-in-out infinite}
    .hud-pulse{animation:hudPulse 1.5s ease-in-out infinite}
"""


def _attr(attrs: str, name: str) -> str | None:
    m = re.search(rf'{name}="([^"]+)"', attrs)
    return m.group(1) if m else None


def find_active_cells(svg: str) -> list[dict]:
    cells: list[dict] = []
    for m in re.finditer(r"<rect\b([^>]*?)/>", svg, re.DOTALL):
        attrs = m.group(1)
        fill = (_attr(attrs, "fill") or "").lower().strip()
        if not fill or fill in EMPTY_FILLS or fill not in ACTIVE_FILLS:
            continue
        try:
            x = float(_attr(attrs, "x") or 0)
            y = float(_attr(attrs, "y") or 0)
            w = float(_attr(attrs, "width") or 0)
            h = float(_attr(attrs, "height") or 0)
        except ValueError:
            continue
        if w == 0 or h == 0:
            continue
        cells.append({"x": x, "y": y, "w": w, "h": h})
    return cells


def make_ghosts(cells: list[dict], target: int) -> tuple[list[str], int]:
    if not cells:
        return [], 0
    n = min(target, len(cells))
    sample = random.sample(cells, n)
    out: list[str] = []
    for i, c in enumerate(sample):
        cx = c["x"] + c["w"] / 2
        cy = c["y"] + c["h"] / 2
        size = c["w"] * 1.8
        delay = random.uniform(0, 4)
        dur = random.uniform(2.5, 4.5)
        cls = "ghost"
        out.append(
            f'<text x="{cx:.2f}" y="{cy:.2f}" font-size="{size:.2f}" '
            f'text-anchor="middle" dominant-baseline="central" '
            f'class="{cls}" style="animation-delay:{delay:.2f}s;animation-duration:{dur:.2f}s">'
            f"👻</text>"
        )
        # Add sparkle next to some ghosts
        if random.random() < 0.4:
            sx = cx + random.uniform(-6, 6)
            sy = cy + random.uniform(-6, 6)
            colors = [GOLD, CYAN, PINK]
            sc = random.choice(colors)
            sd = random.uniform(0, 2)
            out.append(
                f'<circle cx="{sx:.1f}" cy="{sy:.1f}" r="1.5" fill="{sc}" '
                f'class="sparkle" style="animation-delay:{sd:.2f}s"/>'
            )
    return out, n


def make_hud(svg_w: int, total_cells: int, ghost_count: int) -> list[str]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    score = ghost_count * random.randint(2, 5)
    return [
        # Top HUD bar
        f'<rect x="{svg_w/2-180:.1f}" y="0" width="360" height="22" '
        f'rx="11" fill="{PURPLE_BG}" stroke="{PURPLE}" stroke-width="0.8" opacity="0.85"/>',
        f'<text x="{svg_w/2:.1f}" y="15" font-family="Segoe UI,system-ui,sans-serif" font-size="11" '
        f'font-weight="bold" fill="{PURPLE_LIGHT}" text-anchor="middle" letter-spacing="2" '
        f'class="hud-pulse">👻 GHOST HUNT  ·  Score: {score}  ·  👻×{ghost_count}</text>',
        # Bottom info bar
        f'<rect x="10" y="0" width="170" height="18" rx="9" fill="{PURPLE_BG}" '
        f'stroke="{PURPLE_DIM}" stroke-width="0.5" opacity="0.7"/>',
        f'<text x="15" y="12" font-family="monospace" font-size="8" fill="{PURPLE_LIGHT}">'
        f'📦 {total_cells} cells  🕐 {now}</text>',
    ]


def main() -> int:
    if not INPUT.exists():
        print(f"::error::Input SVG not found: {INPUT}", file=sys.stderr)
        return 1

    svg = INPUT.read_text(encoding="utf-8")
    random.seed()

    # 1) Inject CSS
    if "<style" in svg:
        svg = re.sub(r"</style>", EXTRA_CSS + "</style>", svg, count=1)
    else:
        svg = re.sub(r"(<svg[^>]*>)", r"\1<style>" + EXTRA_CSS + "</style>", svg, count=1)

    # 2) Get SVG width
    w_match = re.search(r'<svg[^>]*\swidth="(\d+(?:\.\d+)?)"', svg)
    svg_w = int(float(w_match.group(1))) if w_match else 800

    # 3) Find active cells and place ghosts
    cells = find_active_cells(svg)
    target = random.randint(10, 25)
    ghosts, actual = make_ghosts(cells, target)

    # 4) Build overlays
    hud = make_hud(svg_w, len(cells), actual)

    # 5) Inject before </svg>
    overlays = "\n".join(hud + ghosts)
    svg = svg.replace("</svg>", overlays + "\n</svg>")

    OUTPUT.write_text(svg, encoding="utf-8")
    print(
        f"👻 Ghost Hunt Deluxe: {OUTPUT} ({len(svg):,} bytes, "
        f"{actual} ghosts in {len(cells)} cells)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
